export const mockLocations = [
  "Abelemkpe",
  "Aburi",
  "Accra",
  "Achimota",
  "Adenta",
  "Adjiringanor",
  "Afienya",
  "Airport",
  "Airport Area",
  "Airport Hills",
  "Airport Residential Area",
  "Amasaman",
  "Ashaley Botwe",
  "Ashongman",
  "Ayi Mensa",
  "Beach Road",
  "Buerko",
  "Cantonments",
  "Community 25",
  "Dansoman",
  "Dawhenya",
  "Dodowa",
  "Dzorwulu",
  "East Airport",
  "East Legon",
  "East Legon Hills",
  "Haatso",
  "Kasoa",
  "Kwabenya",
  "Labone",
  "Lakeside Estate",
  "Lashibi",
  "Miotso",
  "Ningo Prampram",
  "North Legon",
  "North Ridge",
  "Ogbojo",
  "Osu",
  "Oyarifa",
  "Oyibi",
  "Pokuase",
  "Prampram",
  "Ridge",
  "Sakumono",
  "Shai Hills",
  "Spintex",
  "Tsopoli",
  "Tema",
  "Teshie",
  "Trasacco",
  "Tse Addo",
  "West Legon",
  "West Trasacco",
];
