export const mockLocations = [
  "Accra, Greater Accra",
  "Kumasi, Ashanti",
  "Tamale, Northern",
  "Cape Coast, Central",
  "Takoradi, Western",
  "Ho, Volta",
  "Koforidua, Eastern",
  "Sunyani, Brong Ahafo",
  "Wa, Upper West",
  "Bolgatanga, Upper East",
  "East Legon, Accra",
  "Cantonments, Accra",
  "Airport Residential, Accra",
  "Labone, Accra",
  "Osu, Accra",
  "Adabraka, Accra",
  "Dansoman, Accra",
  "Tema, Greater Accra",
  "Kasoa, Central",
  "Madina, Greater Accra",
];
